# Generated by Django 5.2.7 on 2025-12-21 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('projects', '0002_projectphase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='projects.projectphase'),
        ),
        migrations.CreateModel(
            name='PhaseEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_escrows_as_employer', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_escrows_as_freelancer', to=settings.AUTH_USER_MODEL)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_escrows', to='projects.project')),
            ],
            options={
                'verbose_name': 'Phase Escrow',
                'verbose_name_plural': 'Phase Escrows',
                'ordering': ['-created_at'],
            },
        ),
    ]
