# Generated by Django 5.2.7 on 2025-12-21 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Phase name (e.g., 'Design Phase', 'Development Phase')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what this phase entails')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid for this phase', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of phase execution (1, 2, 3...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_requested', models.BooleanField(default=False)),
                ('payment_requested_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Phase',
                'verbose_name_plural': 'Project Phases',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
