# Generated by Django 5.2.7 on 2025-11-09 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly version of the title (e.g., 'about-us')", unique=True)),
                ('page_type', models.CharField(choices=[('about', 'About Us'), ('faq', 'FAQ'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('contact', 'Contact'), ('info', 'Information'), ('help', 'Help'), ('custom', 'Custom Page')], default='custom', max_length=20)),
                ('content', models.TextField(help_text='HTML content is allowed')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=255)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO meta keywords (comma-separated)', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage or navigation')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Show link in footer')),
                ('show_in_nav', models.BooleanField(default=False, help_text='Show link in main navigation')),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['order', 'title'],
            },
        ),
    ]
